"""subscriptions + unique entries owner url

Revision ID: 742977e857e3
Revises: 43f452a5cafb
Create Date: 2026-07-06 21:05:32.381627

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "742977e857e3"
down_revision: Union[str, Sequence[str], None] = "43f452a5cafb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("feed_url", sa.String(length=2048), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "feed_url"),
    )
    op.execute(
        """
        DELETE FROM entries e
        USING entries d
        WHERE e.owner_id = d.owner_id
            AND e.url = d.url
            AND e.url IS NOT NULL
            AND (e.created_at, e.id) < (d.created_at, d.id)
        """
    )
    op.create_index(
        op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False
    )
    op.create_index(
        "uq_entries_owner_url",
        "entries",
        ["owner_id", "url"],
        unique=True,
        postgresql_where=sa.text("url IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_entries_owner_url",
        table_name="entries",
        postgresql_where=sa.text("url IS NOT NULL"),
    )
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
