# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search/search.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'search/search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13search/search.proto\x12\tsearch.v1\"?\n\rSearchRequest\x12\x10\n\x08owner_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\r\"#\n\x0eSearchResponse\x12\x11\n\tentry_ids\x18\x01 \x03(\t2N\n\rSearchService\x12=\n\x06Search\x12\x18.search.v1.SearchRequest\x1a\x19.search.v1.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search.search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=34
  _globals['_SEARCHREQUEST']._serialized_end=97
  _globals['_SEARCHRESPONSE']._serialized_start=99
  _globals['_SEARCHRESPONSE']._serialized_end=134
  _globals['_SEARCHSERVICE']._serialized_start=136
  _globals['_SEARCHSERVICE']._serialized_end=214
# @@protoc_insertion_point(module_scope)
