"""telegram_link_update

Revision ID: e0586cc4b76f
Revises:
Create Date: 2026-07-03 21:53:09.350946

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e0586cc4b76f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_links",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("telegram_id"),
    )
    op.create_index(
        op.f("ix_telegram_links_user_id"), "telegram_links", ["user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_telegram_links_user_id"), table_name="telegram_links")
    op.drop_table("telegram_links")
    # ### end Alembic commands ###
