"""add link_codes table


Revision ID: 8a675feeb4cb
Revises: 0f576f3cd3ee
Create Date: 2026-06-30 23:14:40.921638

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a675feeb4cb"
down_revision: Union[str, Sequence[str], None] = "0f576f3cd3ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "link_codes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_link_codes_code_hash"), "link_codes", ["code_hash"], unique=True
    )
    op.create_index(
        op.f("ix_link_codes_user_id"), "link_codes", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_link_codes_user_id"), table_name="link_codes")
    op.drop_index(op.f("ix_link_codes_code_hash"), table_name="link_codes")
    op.drop_table("link_codes")
    # ### end Alembic commands ###
